# Generated by Django 5.1.6 on 2025-03-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view books'), ('can_create', 'Can add new books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_users', 'Can manage users')]},
        ),
    ]
