# Generated by Django 5.1.6 on 2025-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'), ('can_view', 'Can view books')]},
        ),
    ]
